### ISSUE TITLE
Install to system fails

### ISSUE THREAD

**Issue by josfaber** [7anshuai/masq#1]
```
sudo masq --install-system
/usr/local/lib/node_modules/masq/lib/command.js:72
            throw err;
            ^

Error: EEXIST: file already exists, mkdir '/etc/resolver'
    at Error (native)
```

**Comment by 7anshuai** [comment]
It's a bug! When i run `sudo rm -rf /etc/resolver` and reinstall. It will throw this error.

**Comment by 7anshuai** [comment]
Something was wrong in `utils.mkdirp`, simply using the `mkdirp` package to replace it.
It should works now. Thank you!
